# Generated by Django 3.2.6 on 2021-09-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='appointment_by_whom',
            field=models.CharField(default='', max_length=50, verbose_name='Должность кем'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='appointment_to_whom',
            field=models.CharField(default='', max_length=50, verbose_name='Должность кому'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='appointment_whom',
            field=models.CharField(default='', max_length=50, verbose_name='Должность кого'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='', max_length=250, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name_by_whom',
            field=models.CharField(default='', max_length=250, verbose_name='ФИО кем'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name_to_whom',
            field=models.CharField(default='', max_length=250, verbose_name='ФИО кому'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name_whom',
            field=models.CharField(default='', max_length=250, verbose_name='ФИО кого'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='appointment',
            field=models.CharField(default='', max_length=50, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mid_name',
            field=models.CharField(default='', max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='organization',
            field=models.CharField(default='', max_length=50, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='Номер телефона'),
        ),
    ]
