# Generated by Django 3.2.6 on 2022-01-10 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210920_1023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InviteCodeModel',
        ),
    ]
