# Generated by Django 4.0.1 on 2022-01-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_invitecodemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='appointment_by_whom',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='appointment_to_whom',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='appointment_whom',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='full_name_by_whom',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='full_name_to_whom',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='full_name_whom',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mid_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='organization',
        ),
    ]
